Python 데이터 분석과 이미지 처리

Numpy의 기본 사용법

In [1]:
import numpy as np

In [2]:
list_data = [1,2,3]
array = np.array(list_data)

print(array.size)
print(array.dtype)
print(array[2])

3
int32
3


In [3]:
#0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

array2 = np.zeros((4,4), dtype = float)
print(array2)

array3 = np.ones((3,3), dtype = str)
print(array3)

#0부터 9까지 랜덤하기 초기화 된 배열 만들기
array4 = np.random.randint(0,10,(3,3))
print(array4)

#평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0,1,(3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[9 8 2]
 [1 8 7]
 [2 9 7]]
[[ 0.22111733 -0.34868624  0.10429292]
 [ 1.29190753 -1.42045686  0.59087011]
 [-1.2309471   0.14543621 -0.92708284]]


In [4]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [5]:
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))   
print(array2)

[[1 2]
 [3 4]]


In [6]:
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
print(array2)

array3 = np.concatenate([array1,array2], axis = 0) #axis =>아래쪽에 데이터가 합쳐짐.
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [7]:
array = np.arange(8).reshape(2,4)
left, right = np.split(array, [2], axis = 1)
print(left.shape)
print(right.shape)
print(left)
print(right[1][1])

(2, 2)
(2, 2)
[[0 1]
 [4 5]]
7
