Python 데이터 분석과 이미지 처리

Numpy의 기본 사용법

In [2]:
import numpy as np

In [2]:
list_data = [1,2,3]
array = np.array(list_data)

print(array.size)
print(array.dtype)
print(array[2])

3
int32
3


In [3]:
#0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

array2 = np.zeros((4,4), dtype = float)
print(array2)

array3 = np.ones((3,3), dtype = str)
print(array3)

#0부터 9까지 랜덤하기 초기화 된 배열 만들기
array4 = np.random.randint(0,10,(3,3))
print(array4)

#평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0,1,(3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[9 8 2]
 [1 8 7]
 [2 9 7]]
[[ 0.22111733 -0.34868624  0.10429292]
 [ 1.29190753 -1.42045686  0.59087011]
 [-1.2309471   0.14543621 -0.92708284]]


In [4]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])
print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [5]:
array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))   
print(array2)

[[1 2]
 [3 4]]


In [6]:
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
print(array2)

array3 = np.concatenate([array1,array2], axis = 0) #axis =>아래쪽에 데이터가 합쳐짐.
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [7]:
array = np.arange(8).reshape(2,4)
left, right = np.split(array, [2], axis = 1)
print(left.shape)
print(right.shape)
print(left)
print(right[1][1])

(2, 2)
(2, 2)
[[0 1]
 [4 5]]
7


Numpy의 기본 연산

브로드캐스트

In [4]:
array = np.random.randint(1,10,size=4).reshape(2,2)
print(array)

result_array = array*10
print(result_array)

[[5 9]
 [1 5]]
[[50 90]
 [10 50]]


In [5]:
array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)
array3 = array1 + array2
print(array3)

[[0 2]
 [2 4]]


In [7]:
array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1,array2],axis=0)
array4 = np.arange(0,4).reshape(4,1)

print(array3+array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


마스킹

In [18]:
array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [24]:
array = np.arange(16).reshape(4,4)
print("최댓값: ", np.max(array))
print("최솟값: ", np.min(array))
print("합계: ", np.sum(array))
print("평균: ", np.mean(array))

print(array)
print("합계: ", np.sum(array,axis=0))

최댓값:  15
최솟값:  0
합계:  120
평균:  7.5
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계:  [24 28 32 36]


Numpy의 활용

In [25]:
#단일 객체 저장 및 불러오기
array = np.arange(0,10)
np.save('saved.npy', array)

In [27]:
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
#복수 객체 저장 및 불러오기
array1 = np.arange(0,10)
array2 = np.arange(10,20)
np.savez('saved.npz',array1=array1, array2=array2)

In [30]:
data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [32]:
#Numpy 원소 오름차순 정렬
array = np.array([5,9,10,3,1])
array.sort()
#내립차순 정렬
print(array[::-1])

[10  9  5  3  1]


In [34]:
#각 열을 기준으로 정렬
array = np.array([[5,9,10,3,1],[8,3,4,2,5]])
print(array)
array.sort(axis=0)
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [42]:
#균일한 간격으로 데이터 생성
array = np.linspace(0,10,5)
print(array)

#난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0,10,(2,3)))

#Numpy 배열 객체 복사
array1 = np.arange(0,10)
array2 = array1.copy()
array2[0] = 99
print(array1)

#중복된 원소 제거
array = np.array([1,1,2,2,3,3,4])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
